import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { join } from 'path';

interface InvoicePDFData {
    invoice_number: string;
    customer_name: string;
    customer_phone: string;
    customer_gstin?: string;
    customer_state?: string;
    customer_state_code?: string;
    amount: number;
    taxable_amount: number;
    gst_rate: number;
    gst_amount: number;
    cgst_amount: number;
    sgst_amount: number;
    igst_amount: number;
    hsn_code: string;
    gst_type: string;
    amount_paid: number;
    status: string;
    generated_at: number;
    due_date?: number;
    design_name: string;
    fabric_type?: string;
    quantity_meters: number;
    price_per_meter: number;
    generated_by?: string;
    seller_name?: string;
    seller_phone?: string;
    seller_address?: string;
    seller_gstin?: string;
    seller_logo?: string;
}

export async function generateInvoicePDFServer(data: InvoicePDFData): Promise<{ relativePath: string; buffer: Buffer }> {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    // Colors ( Surat Premium Textile ERP - Professional Monochrome & Slate Slate Accent )
    const colorTextPrimary = '#1e293b'; // Slate 800
    const colorTextSecondary = '#64748b'; // Slate 500
    const colorBorder = '#cbd5e1'; // Slate 300
    const colorBgAlt = '#f8fafc'; // Slate 50

    // Helper functions
    const formatCurrency = (val: number) => `INR ${val.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
    const formatDate = (timestamp: number) => {
        const d = new Date(timestamp * 1000);
        return d.toLocaleDateString('en-US', {
            year: 'numeric', month: 'short', day: 'numeric'
        });
    };

    // Page layout coordinates (Margins: 15mm)
    const margin = 15;
    const startY = 15;
    const pageWidth = 210;
    const contentWidth = pageWidth - (2 * margin);

    // ==========================================
    // 1. HEADER SECTION (Left & Right Split)
    // ==========================================
    
    // Left: Business Info
    let currentY = startY;
    if (data.seller_logo) {
        try {
            // Assume 25x25 box for logo
            doc.addImage(data.seller_logo, margin, currentY, 25, 25);
            currentY += 30;
        } catch (e) {
            console.error('Failed to add invoice logo:', e);
            currentY = startY;
        }
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(colorTextPrimary);
    doc.text(data.seller_name || 'FABRICOS TEXTILES', margin, currentY);
    currentY += 5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(colorTextSecondary);
    
    const address = data.seller_address || 'Plot No. 45-48, Sachin GIDC, Surat, Gujarat - 394230';
    doc.text(address, margin, currentY);
    currentY += 4;
    const phoneStr = data.seller_phone ? `Phone: ${data.seller_phone}` : 'Phone: +91 98765 43210';
    doc.text(`${phoneStr} | E-mail: billing@fabricos.com`, margin, currentY);
    currentY += 4;
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(colorTextPrimary);
    doc.text(`GSTIN: ${data.seller_gstin || '24AAECF1234A1Z0'}`, margin, currentY);

    // Right: Document Title & Badges
    const rightX = pageWidth - margin;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(colorTextPrimary);
    doc.text('TAX INVOICE / CHALLAN', rightX, startY + 4, { align: 'right' });

    // Status Badge background & text
    let badgeColor = '#64748b'; // default pending/unpaid
    const normalizedStatus = data.status.toLowerCase();
    if (normalizedStatus === 'paid') {
        badgeColor = '#10b981'; // Green
    } else if (normalizedStatus === 'overdue') {
        badgeColor = '#ef4444'; // Red
    } else if (normalizedStatus === 'partial') {
        badgeColor = '#f59e0b'; // Amber
    }

    doc.setFillColor(badgeColor);
    doc.roundedRect(pageWidth - margin - 24, startY + 7, 24, 5, 0.5, 0.5, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor('#ffffff');
    doc.text(data.status.toUpperCase(), pageWidth - margin - 12, startY + 10.5, { align: 'center' });

    // Metadata lines on the Right
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(colorTextSecondary);
    currentY = startY + 16;
    doc.text(`Invoice No: ${data.invoice_number}`, rightX, currentY, { align: 'right' });
    currentY += 4;
    doc.text(`Date: ${formatDate(data.generated_at)}`, rightX, currentY, { align: 'right' });
    if (data.due_date) {
        currentY += 4;
        doc.text(`Due Date: ${formatDate(data.due_date)}`, rightX, currentY, { align: 'right' });
    }
    currentY += 4;
    doc.text(`Generated By: ${data.generated_by || 'System'}`, rightX, currentY, { align: 'right' });
    currentY += 4;
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(7.5);
    doc.text('E. & O.E.', rightX, currentY, { align: 'right' });

    // Header divider line
    currentY += 4;
    doc.setDrawColor(colorBorder);
    doc.setLineWidth(0.3);
    doc.line(margin, currentY, pageWidth - margin, currentY);

    // ==========================================
    // 2. CUSTOMER DETAILS (Soft Card Box)
    // ==========================================
    currentY += 5;
    const showCustGst = !!data.customer_gstin;
    const cardHeight = showCustGst ? 22 : 18;
    doc.setDrawColor(colorBorder);
    doc.setFillColor(colorBgAlt);
    // Draw card border
    doc.roundedRect(margin, currentY, contentWidth, cardHeight, 1, 1, 'FD');

    // Card content
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(colorTextSecondary);
    doc.text('BILL TO / SHIP TO (CUSTOMER)', margin + 4, currentY + 4.5);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10.5);
    doc.setTextColor(colorTextPrimary);
    doc.text(data.customer_name, margin + 4, currentY + 10);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(colorTextSecondary);
    let custInfoLine = `Phone: ${data.customer_phone}`;
    if (data.customer_state) {
        custInfoLine += ` | State: ${data.customer_state} (${data.customer_state_code || ''})`;
    }
    doc.text(custInfoLine, margin + 4, currentY + 14);

    if (showCustGst) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(colorTextPrimary);
        doc.text(`GSTIN: ${data.customer_gstin}`, margin + 4, currentY + 18);
    }

    // ==========================================
    // 3. PRODUCT TABLE (Surat Textile Style)
    // ==========================================
    currentY += cardHeight + 5;

    const tableHeaders = [
        'Design Name',
        'HSN Code',
        'Fabric Type',
        'Meters (Mtr)',
        'Rate / Mtr',
        'GST Rate',
        'Taxable Amount'
    ];

    const tableRows = [
        [
            data.design_name,
            data.hsn_code || '5407',
            data.fabric_type || 'Printed Fabric',
            `${data.quantity_meters.toFixed(2)} Mtr`,
            `INR ${data.price_per_meter.toFixed(2)}`,
            `${data.gst_rate}%`,
            formatCurrency(data.taxable_amount)
        ]
    ];

    autoTable(doc, {
        startY: currentY,
        head: [tableHeaders],
        body: tableRows,
        theme: 'plain',
        margin: { left: margin, right: margin },
        headStyles: {
            fillColor: '#f1f5f9', // Slate 100
            textColor: colorTextPrimary,
            font: 'helvetica',
            fontStyle: 'bold',
            fontSize: 8.5,
            halign: 'left',
            cellPadding: 3.5,
            lineWidth: 0.1,
            lineColor: colorBorder
        },
        bodyStyles: {
            textColor: colorTextPrimary,
            font: 'helvetica',
            fontSize: 8.5,
            cellPadding: 3.5,
            lineWidth: 0.1,
            lineColor: colorBorder
        },
        columnStyles: {
            3: { halign: 'right' },
            4: { halign: 'right' },
            5: { halign: 'center' },
            6: { halign: 'right' }
        },
        styles: {
            overflow: 'linebreak'
        }
    });

    let finalY = (doc as any).lastAutoTable.finalY + 6;

    // ==========================================
    // 4. FINANCIAL SUMMARY
    // ==========================================
    const summaryWidth = 75;
    const summaryX = pageWidth - margin - summaryWidth;

    // Subtotal
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(colorTextSecondary);
    doc.text('Taxable Value (Subtotal):', summaryX, finalY);
    doc.setTextColor(colorTextPrimary);
    doc.text(formatCurrency(data.taxable_amount), rightX, finalY, { align: 'right' });
    finalY += 4.5;

    if (data.gst_type === 'CGST_SGST') {
        // CGST
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(colorTextSecondary);
        doc.text(`CGST (${(data.gst_rate / 2).toFixed(1)}%):`, summaryX, finalY);
        doc.setTextColor(colorTextPrimary);
        doc.text(formatCurrency(data.cgst_amount), rightX, finalY, { align: 'right' });
        finalY += 4.5;

        // SGST
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(colorTextSecondary);
        doc.text(`SGST (${(data.gst_rate / 2).toFixed(1)}%):`, summaryX, finalY);
        doc.setTextColor(colorTextPrimary);
        doc.text(formatCurrency(data.sgst_amount), rightX, finalY, { align: 'right' });
        finalY += 4.5;
    } else if (data.gst_type === 'IGST') {
        // IGST
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(colorTextSecondary);
        doc.text(`IGST (${data.gst_rate.toFixed(1)}%):`, summaryX, finalY);
        doc.setTextColor(colorTextPrimary);
        doc.text(formatCurrency(data.igst_amount), rightX, finalY, { align: 'right' });
        finalY += 4.5;
    } else {
        // GST (0%)
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(colorTextSecondary);
        doc.text('GST (0%):', summaryX, finalY);
        doc.setTextColor(colorTextPrimary);
        doc.text(formatCurrency(0), rightX, finalY, { align: 'right' });
        finalY += 4.5;
    }

    // Line separator
    doc.setDrawColor(colorBorder);
    doc.setLineWidth(0.2);
    doc.line(summaryX, finalY, rightX, finalY);
    finalY += 5.5;

    // Grand Total
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(colorTextPrimary);
    doc.text('Grand Total (Incl. GST):', summaryX, finalY);
    doc.text(formatCurrency(data.amount), rightX, finalY, { align: 'right' });
    finalY += 5;

    // Balance/Payment Info
    if (data.amount_paid > 0) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8.5);
        doc.setTextColor(colorTextSecondary);
        doc.text('Amount Received:', summaryX, finalY);
        doc.setTextColor('#10b981'); // Green
        doc.text(`- ${formatCurrency(data.amount_paid)}`, rightX, finalY, { align: 'right' });
        finalY += 4.5;

        doc.setDrawColor(colorBorder);
        doc.line(summaryX, finalY - 1, rightX, finalY - 1);
        finalY += 3.5;

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9.5);
        doc.setTextColor(colorTextPrimary);
        doc.text('Balance Due:', summaryX, finalY);
        const balance = Math.max(0, data.amount - data.amount_paid);
        doc.text(formatCurrency(balance), rightX, finalY, { align: 'right' });
    }

    // ==========================================
    // 5. FOOTER (T&C, Signatures, Thanks)
    // ==========================================
    // Push elements to the bottom of the page to look neat
    const footerStartY = 250;

    // Separator line
    doc.setDrawColor(colorBorder);
    doc.setLineWidth(0.3);
    doc.line(margin, footerStartY, pageWidth - margin, footerStartY);

    // Left: Terms and Conditions
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(colorTextPrimary);
    doc.text('TERMS & CONDITIONS:', margin, footerStartY + 5);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    doc.setTextColor(colorTextSecondary);
    doc.text('1. Goods once sold will not be accepted back or exchanged.', margin, footerStartY + 8.5);
    doc.text('2. Interest @ 18% p.a. will be levied if payment is not cleared by due date.', margin, footerStartY + 11.5);
    doc.text('3. All disputes are subject to Surat Jurisdiction.', margin, footerStartY + 14.5);

    // Center: Thanks message
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(colorTextPrimary);
    doc.text('Thank you for your business!', pageWidth / 2, footerStartY + 11, { align: 'center' });

    // Right: Authorized Signature Placeholder
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7.5);
    doc.setTextColor(colorTextPrimary);
    doc.text(`For, ${data.seller_name?.toUpperCase() || 'FABRICOS TEXTILES'}`, rightX, footerStartY + 5, { align: 'right' });
    
    // Line for signature
    doc.setDrawColor(colorBorder);
    doc.setLineWidth(0.2);
    doc.line(pageWidth - margin - 45, footerStartY + 16, rightX, footerStartY + 16);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6.5);
    doc.setTextColor(colorTextSecondary);
    doc.text('Authorized Signatory', rightX, footerStartY + 19, { align: 'right' });

    // Output to Buffer
    const arrayBuffer = doc.output('arraybuffer');
    const buffer = Buffer.from(arrayBuffer);

    return {
        buffer
    };
}
